#this workflow will build a java project with gradel


name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
       
    - name: Grant execute permission for gradlew
      run: cloud +x gradlew
      
    - name: Build with gradle
      run: ./gradlew build
    - name: Build with gradle
      run: ./gradlew build

    - name: list build output
      run: ls -l build/libs
    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
         image:
         registry:docker.io
         username:${{secrets.username }}
         password:${{secrets.password }}


    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
