#this workflow will build a java project with gradel
#For more information see:http://help.github.co /actions/language-and-framework-guides/building=and-testing-java-with-gradle 

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
       
    - name: Grant execute permission for gradlew
      run: cloud +x gradlew
      
    - name: Build with gradle
      run: ./gradlew build
    - name: Build with gradle
      run: ./gradlew build

    - name: list build output
      run: ls -l build/libs
    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
         image: sireesha03/sirimini-pro2
         registry: docker.io
         username: ${{secrets.username }}
         password: ${{secrets.password }}


    
